/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'quantity' : number, 'product' : Product }
export interface OrderType {
  'id' : bigint,
  'status' : Status,
  'createdAt' : Time,
  'user' : Principal,
  'totalAmount' : bigint,
  'items' : Array<CartItem>,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : string,
  'price' : bigint,
}
export interface Service {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : string,
  'priceLabel' : string,
}
export interface ServiceInquiry {
  'id' : bigint,
  'createdAt' : Time,
  'user' : Principal,
  'message' : string,
  'contactEmail' : string,
  'serviceId' : bigint,
}
export type Status = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'processing' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addService' : ActorMethod<[Service], undefined>,
  'addToCart' : ActorMethod<[bigint, number], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getInquiries' : ActorMethod<[], Array<ServiceInquiry>>,
  'getOrders' : ActorMethod<[], Array<OrderType>>,
  'getProducts' : ActorMethod<[[] | [string]], Array<Product>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[], undefined>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'removeProduct' : ActorMethod<[bigint], undefined>,
  'removeService' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitInquiry' : ActorMethod<[bigint, string, string], undefined>,
  'updateCartItem' : ActorMethod<[bigint, number], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, Status], undefined>,
  'updateProduct' : ActorMethod<[bigint, Product], undefined>,
  'updateService' : ActorMethod<[bigint, Service], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];