/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'priceLabel' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CartItem = IDL.Record({
  'quantity' : IDL.Nat32,
  'product' : Product,
});
export const Time = IDL.Int;
export const ServiceInquiry = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'message' : IDL.Text,
  'contactEmail' : IDL.Text,
  'serviceId' : IDL.Nat,
});
export const Status = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'processing' : IDL.Null,
});
export const OrderType = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(CartItem),
});
export const UserRecord = IDL.Record({
  'principal' : IDL.Principal,
  'joinedAt' : Time,
  'role' : UserRole,
  'profileName' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'addService' : IDL.Func([Service], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat32], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getInquiries' : IDL.Func([], [IDL.Vec(ServiceInquiry)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(OrderType)], ['query']),
  'getProducts' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Product)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsers' : IDL.Func([], [IDL.Vec(UserRecord)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([], [], []),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'removeProduct' : IDL.Func([IDL.Nat], [], []),
  'removeService' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitInquiry' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat32], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, Status], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
  'updateService' : IDL.Func([IDL.Nat, Service], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'priceLabel' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CartItem = IDL.Record({ 'quantity' : IDL.Nat32, 'product' : Product });
  const Time = IDL.Int;
  const ServiceInquiry = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'message' : IDL.Text,
    'contactEmail' : IDL.Text,
    'serviceId' : IDL.Nat,
  });
  const Status = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'processing' : IDL.Null,
  });
  const OrderType = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(CartItem),
  });
  const UserRecord = IDL.Record({
    'principal' : IDL.Principal,
    'joinedAt' : Time,
    'role' : UserRole,
    'profileName' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'addService' : IDL.Func([Service], [], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat32], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getInquiries' : IDL.Func([], [IDL.Vec(ServiceInquiry)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(OrderType)], ['query']),
    'getProducts' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsers' : IDL.Func([], [IDL.Vec(UserRecord)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([], [], []),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'removeProduct' : IDL.Func([IDL.Nat], [], []),
    'removeService' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitInquiry' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat32], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, Status], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
    'updateService' : IDL.Func([IDL.Nat, Service], [], []),
  });
};

export const init = ({ IDL }) => { return []; };